# 如果包含了这个配置文件，runner.fiscobcos2也需要为true，才会使适配fiscobcos2的部分生效
runner:
  fiscobcos2: true

# sdk
fiscobcos2sdk:

  orgName: orgTest
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  timeout: 30000
  idleTimeout: 30000
  keepAlive: 60
  #0:standard, 1:guomi
  encryptType: 0

#key store
fiscobcos2userkey:
  store_file: "./key/ECC/keyStoreUser.txt"  #  k1 key file to save keyUser.
  #store_file: "./key/GM/keyStoreUser.txt"  # gm key file to save keyUser.

########################################################################
# 配置 Truora 连接的链和群组信息（证书和地址）:
#   1. 同一条链可以配置多个群组
#   2. 可以配置多条链
########################################################################
fiscobcos2channels:
  configs:
    ## 第一条链的连接信息，证书，群组列表和 IP:Port
    - chainId: 1
      caCert: classpath:conf/ca.crt
      sslCert: classpath:conf/sdk.crt
      sslKey: classpath:conf/sdk.key
      all-channel-connections:
        - group-id: 1
          connections-str:
            # node listen_ip:channel_listen
            - 127.0.0.1:${FISCO_BCOS_PORT:20200}
        ## 群组 2 的信息
        #- group-id: 2
        #  connections-str:
        #    - 127.0.0.1:20200

    ## 第二条链的连接信息，证书，群组列表以及对应的 IP:Port
    #- chainId: 2
    #  caCert: classpath:2/ca.crt
    #  sslCert: classpath:2/node.crt
    #  sslKey: classpath:2/node.key
    #  all-channel-connections:
    #    - group-id: 1
    #      connections-str:
    #        - 127.0.0.1:20200




#fisco-bcos 2.2 or latest
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id14
########################################################################
# 配置事件监听：
#   1. 配置 Truora 需要监听的链（ChainId）和群组（groupId）
#   2. 配置的 chainId 和 groupId 需要配置在 group-channel-connections-configs
########################################################################
fiscobcos2event:
  eventRegisters:
    # list of EventRegister objects. Use default value when property not configured.
    # Oracle contracts will be auto deployed when contractAddress is blank
    - {chainId: 1, groupId: 1}
    #- {chain: 1, group: 2}
    #- {chain: 2, group: 1}
    #- {chain: 2, group: 2}

