# 如果包含了这个配置文件，runner.fiscobcos2也需要为true，才会使适配fiscobcos2的部分生效
runner:
  fiscobcos3: true

#----------------------------------------------------------
# fisco-bcos 3.x
#----------------------------------------------------------
fiscobcos3:
  platform: fiscobcos3
  # 可忽略，每个chain/group可配置不同的key file
  defaultKeyfile: "./ECC/keyStoreUser.txt"
  sdkconfigs:
    # 配置指向一到多个链/群组实例的sdk。
    # fisco bcos3.x版本的sdk使用独立的toml配置文件，每个链客户端实例写一个toml配置，里面可以配置连接多个节点
    chain0: bcos3sdk_config.toml
    #chain1: bcos3sdk_config_1.toml
  eventRegisters:
    # 配置一到多个chain/group的Oracle/VRF监听服务，如果数据库里没有合约地址记录，会做自动部署
    - chainId: chain0
      groupId: group0
      fromBlock:
      toBlock:
      #是否启动oracleCore合约监听，一般是要起来的，除非有别的实现，可以不启动这个版本
      startOracleCore : true
      #是否启动VRF25519Core合约监听，在fisco bcos3上推荐
      startVRF25519: true
      #是否启动VRFK1Core合约监听，面向VRFK1算法的实现不支持国密，在国密版本上无法启动，在fisco bcos3上推荐使用VRF25519
      startVRFK1: false
      #为每个监听实例指定不同的keyflie
      keyfile: "./ECC/keyStoreUser.txt"


