#-------------------------------------
# 供测试和体验的一些配置，仅供参考
dapps:
  APISample:
    chainId: chain0
    groupId: group0
    contractAddress:
    lastaddress: '0x91e5fed11e92b1eb96f5d1c472d2649f09f00b55'
    url: plain(https://www.random.org/integers/?num=10&min=1&max=1000&col=1&base=10&format=plain&rnd=new)
  APISampleString:
    contractAddress: '0x1234'
    url: plain(https://www.random.org/integers/?num=10&min=1&max=1000&col=1&base=10&format=plain&rnd=new)
  GeneralOracle:
    chainId: chain0
    groupId: group0
    contractAddress: '0xae9aed104e0458dd08bd3d93d88bec2a8bd60cc3'
    lastaddress: ''
    url: json(https://api.exchangerate-api.com/v4/latest/CNY).rates.JPY
    timesAmount: 100
    returnType : 0
    url1: https://www.random.org/integers/?num=10&min=1&max=1000&col=1&base=10&format=plain&rnd=new
    timesAmount1: 1
    returnType1 : 0
    url2: json(https://api.exchangerate-api.com/v4/latest/CNY).rates.KES
    timesAmount2: 100
    returnType2: 0
    url3: '{"name":"HashUrl","url":"http://www.qq.com/"}'
    timesAmount3: 1
    returnType3 : 0
